stages:
  - build

build-and-test-frontend:
  stage: build
  image: node:latest
  cache:
    key: npm-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
    paths:
      - frontend/node_modules/
    policy: pull-push
  before_script:
    - cd frontend
    - npm install
  script:
    - echo "Building..."
    - npm run build    
    - echo "Build successful"
    - echo "Running unit tests..."
    - npm run test
    - echo "Tests completed"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always