Use SpeakATX;

CREATE TABLE IF NOT EXISTS Communities ( 
	Community_id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Size INT NOT NULL,
    Language VARCHAR(255) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Type VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Jobs ( 
	Jobs_id INT PRIMARY KEY AUTO_INCREMENT,
    Company VARCHAR(255) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Pay FLOAT NOT NULL,
    Location VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Services (
    Services_id INT PRIMARY KEY AUTO_INCREMENT,
    Company VARCHAR(255) NOT NULL,
    Language VARCHAR(255) NOT NULL,
    Rating FLOAT NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Pricing FLOAT NOT NULL
);

SHOW TABLES;